### ISSUE TITLE
Use a finer font

### ISSUE THREAD

**Issue by Sioxas** [lannonbr/vscode-js-annotations#16]
What are you wanting to see improved / introduced?
It would be better the font like this ![image](https://user-images.githubusercontent.com/9740581/45015276-c9402b00-b053-11e8-947d-4d4deba1c4f7.png)

**Comment by lannonbr** [comment]
@Sioxas How about opening two configs to set the font weight and if the annotations are italicized so it can be defined by the user how the annotations are presented

**Comment by Sioxas** [comment]
Good idea

**Comment by lannonbr** [comment]
Implemented in 0.7.0. The marketplace is still down for now but it can be manually installed from here on github: https://github.com/lannonbr/vscode-js-annotations/releases/tag/0.7.0
