### ISSUE TITLE
Hints is incorrect with typescript

### ISSUE THREAD

**Issue by Sioxas** [lannonbr/vscode-js-annotations#17]
VS Code Version:1.26.1
Extension Version:0.6.1

What's the issue: hints is incorrect with typescript
![image](https://user-images.githubusercontent.com/9740581/45015745-3607f500-b055-11e8-9ba4-f74211a5c486.png)

**Comment by lannonbr** [comment]
The issue here is when parsing the definition it is grabbing the first word. I will fix this tonight so it grabs the param name in all cases

**Comment by lannonbr** [comment]
And fixed as seen below. this is available in 0.7.1

<img width="669" alt="screen shot 2018-09-04 at 8 16 41 pm" src="https://user-images.githubusercontent.com/3685876/45064022-77ad9580-b07f-11e8-9e15-c8d23d3691f3.png">
