### ISSUE TITLE
Annotations sometimes wrong.

### ISSUE THREAD

**Issue by Sioxas** [lannonbr/vscode-js-annotations#21]
VS Code Version: 1.26.1
Extension Version: 0.7.1

What's the issue: annotations sometimes wrong.
![image](https://user-images.githubusercontent.com/9740581/45129592-2b657100-b1b7-11e8-80c2-af8ab0d987d0.png)

**Comment by lannonbr** [comment]
I will dig into this tomorrow evening. Thanks for the bug report!

**Comment by lannonbr** [comment]
Fixed in 0.7.2. Closing
