### ISSUE TITLE
Annotations not appearing in TSX / JSX files

### ISSUE THREAD

**Issue by LaurensBosscher** [lannonbr/vscode-js-annotations#37]
VS Code Version:
1.28.0

Extension Version:
0.9.0

What's the issue:

I'm not sure how to debug this issue. I've installed the extension but I'm not seeing the desired effect.  See screenshot:

![schermafbeelding 2018-10-09 om 09 42 22](https://user-images.githubusercontent.com/13363196/46653918-a8fe1180-cba7-11e8-92ac-3a58e1411666.png)

As you can see in the screenshot VSCode has figured out the parameter name (route) but it's not displayed. I've tried to toggle the annotations but that made no difference. 

I do get two suggestions from VSCode because we're using Flow but the JS/TS extension is still enabled.

**Comment by Titozzz** [comment]
At the bottom of your file there is prob written Javascript React. It only works if you set it to Javascript. Should be fixable I guess

**Comment by Titozzz** [comment]
@lannonbr Is there any obstacle to support JSX/TSX (javascriptreact/typescriptreact) ?

**Comment by lannonbr** [comment]
@LaurensBosscher and @Titozzz, I will have to try later if I can support the two formats, but as long as the parsers which I use in the extension (Esprima for JS, Recast's TS parser for TS) support JSX / TSX, I should be able to just add those two formats. I will test it out later and if it is successful, I will push a new update.

**Comment by LaurensBosscher** [comment]
@Titozzz This was indeed in a React component but in JS files (with type "Javascript" in the lower right corner) this also doesn't display.

See attached screenshot:

![schermafbeelding 2018-10-09 om 14 59 49](https://user-images.githubusercontent.com/13363196/46671035-0445f900-cbd4-11e8-9b9c-7bba3136256a.png)

This was the simplest case I could think of, console.log should display "message", right? Both the internal JS parser and Flow do detect this and show this in the overview, this file only contains JS (no JSX) and the type is configured correctly for Javascript (as visible in the lower right corner).

Is there any way I can further debug this? Might this be related to our usage of Flow?

**Comment by lannonbr** [comment]
If you could possibly share a small code snippet, I could try later today testing it and seeing what breaks when I debug my extension. As well, if you want to try debugging it yourself and send in a possible PR if you can find a way to resolve it, I am happy to receive contributions.

As well with this, let me go make another issue to write some docs to explain how to debug the extension so if someone has never worked on vscode extensions before, I can be welcoming to them as well.

**Comment by Titozzz** [comment]
Well, i've got the same issue @LaurensBosscher, whenever I create a new file, for example test.js and write console.log(), messages displays fine when I set language to Javascript, but if I set language to javascript in one of my more complex files it's not working 😢 . I'll try to debug if you explain how to :)

**Comment by lannonbr** [comment]
For a TDLR, clone the repo down, run `npm install`, put in some breakpoints in some files, and if you open the debug panel in VS Code and run the "Extension" config and it will open up an instance of vscode with the extension loaded.

you likely will want to put some breakpoints in [parser.ts](https://github.com/lannonbr/vscode-js-annotations/blob/master/src/parser.ts) and [decorator.ts](https://github.com/lannonbr/vscode-js-annotations/blob/master/src/decorator.ts)

**Comment by lannonbr** [comment]
So I dug into some things and [Babel's Parser](https://babeljs.io/docs/en/next/babel-parser.html) which is what recast is using for Typescript does support JSX/TSX so I will dig into this given it does support them.

**Comment by Titozzz** [comment]
So cool ❤️

**Comment by lannonbr** [comment]
As well, Facebook themselves have a doc on the AST for JSX and show the tools that supports it: https://github.com/facebook/jsx/blob/master/AST.md#tools-that-work-with-jsx-ast

**Comment by lellimecnar** [comment]
I'm seeing this same thing with the type set to `Babel JavaScript`

**Comment by rafistrauss** [comment]
Note that if the file contains JSX at all, the annotations will not be displayed:
![screen shot 2018-11-15 at 1 50 02 pm](https://user-images.githubusercontent.com/4576234/48574591-97620500-e8dd-11e8-9263-e063c64b0d5f.png)

vs.

![screen shot 2018-11-15 at 1 50 16 pm](https://user-images.githubusercontent.com/4576234/48574598-9c26b900-e8dd-11e8-8b82-93de22ad86a8.png)

**Comment by lannonbr** [comment]
Both TSX and JSX files now work. @LaurensBosscher @Titozzz, If I give you the dev build of the next version of the extension, would you two be willing to test this out?

**Comment by lannonbr** [comment]
Here's the pre-release: https://github.com/lannonbr/vscode-js-annotations/releases/tag/0.10.0-dev. Download that .vsix file and you can install that in VS Code as described here: https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix

**Comment by rafistrauss** [comment]
@lannonbr I tried it out over the weekend - seems to work great, thanks!

**Comment by Titozzz** [comment]
awesome, I'll test it too :)
