### ISSUE TITLE
annotationForeground is not working

### ISSUE THREAD

**Issue by moshfeu** [lannonbr/vscode-js-annotations#38]
VS Code Version: 1.28.0
Extension Version: 0.9.0

What's the issue:

Maybe I don't know how to set it  but it seems that `jsannotations.annotationForeground` is not working. I put it in User Settings file (`settings.json`) and I get `Unknown configuration setting` and the colors stays grey as it's by default.

Thanks!

**Comment by lannonbr** [comment]
Hey @moshfeu,

So the annotationForeground is a theme customization, so did you try putting it in the `workbench.colorCustomizations` setting in the User Settings?

Here's an example of such:

```json
// Settings.json
{  
  "workbench.colorCustomizations": {
    "jsannotations.annotationForeground": "#ff0000"
  }
}
```

As well, if you want to customize it for a particular theme, you can insert it as such where the element in the square brackets is the name of the theme you want to customize it for:

```json
// Settings.json
{
  "workbench.colorCustomizations": {
    "[Shades of Purple]": {
      "jsannotations.annotationForeground": "#c0c"
    }
  }
}

Hope this helps out!
