### ISSUE TITLE
'jsannotations.annotationForeground' property issue

### ISSUE THREAD

**Issue by endalgo-jhpark** [lannonbr/vscode-js-annotations#42]
VS Code Version:
Extension Version:

What's the issue:
https://marketplace.visualstudio.com/items?itemName=lannonbr.vscode-js-annotations#overview
I've tried to change foreground color of annotations following your explanation 'Themable Colors', but it did not work.
speech bubble says, cannot find 'jsannotations.annotationForeground' property.

How can I fix this problem?

**Comment by lannonbr** [comment]
See #38

**Comment by endalgo-jhpark** [comment]
oh, it has already answered.

I feel sorry and thank you for providing useful sources :)
