### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by anurbol** [lannonbr/vscode-js-annotations#5]
Hi there! Thanks for the extension, it's cool! 

Can Typescript support be added to it? You know, typescript is a JS superset, mostly compatible, at least function calls and declarations are mostly the same.

I tried to change this line but with no success:
https://github.com/lannonbr/vscode-js-annotations/blob/a1167ef476741ef59a4fc503e0cfa6ab7cde49e1/src/extension.ts#L42

I am not familiar with VSCode extensions apparently :smiley:

**Comment by lannonbr** [comment]
I am interested in adding Typescript support. I currently use Esprima to find function calls within the code, and I am not sure if it will parse TS files, but I will dig into it and try finding a solution so this supports Typescript in an upcoming release.

**Comment by anurbol** [comment]
Oh. I guess Esprima is not able to do that. Well, unfortunately I have no time to help you in this, but at least I can suggest you very good tool if you are interested https://github.com/dsherret/ts-simple-ast. Used it, for similar purpose.

**Comment by lannonbr** [comment]
It looks like [recast](https://github.com/benjamn/recast) may work given I can switch the underlying parser to also include a TS parser

**Comment by anurbol** [comment]
Cool. I didn't even know it existed. Thanks for the response! Good luck.

**Comment by lannonbr** [comment]
And with a little bit of work, I just pushed up v0.3.0 and it is all set. Typescript function calls will now get annotations the same way as JS.

Closing.

**Comment by anurbol** [comment]
Wow. That's amazing. Not bad, not bad :astonished:
