### ISSUE TITLE
Option to disable leading whitespace for first paramater

### ISSUE THREAD

**Issue by magnattic** [lannonbr/vscode-js-annotations#62]
It would be awesome if you could disable the whitespacing in front of the first parameter name.

![screenshot from 2019-01-25 16-06-29](https://user-images.githubusercontent.com/7560166/51754114-c3f38380-20bb-11e9-8db0-39dbc9d41f38.png)

Because I dont have any trailing whitespaces before my parentheses, this looks rather weird. I'd prefer to only have spaces between parameters.

Even better: Detect if there was a whitespace and only add one in front of the parameter name if it was already there.

**Comment by lannonbr** [comment]
Thanks for the suggestion. I will add this into the roadmap for my next release. It shouldn't be too difficult to add a config to turn off the first space or your 2nd suggestion of making sure there's only one space between the open paren and the annotation
