### ISSUE TITLE
The prompt message is incorrect

### ISSUE THREAD

**Issue by wtklbm** [lannonbr/vscode-js-annotations#63]
VS Code Version: 1.30.1
![2019-02-03_16 20 23](https://user-images.githubusercontent.com/26459487/52174502-aa46f000-27cf-11e9-9ed1-c5d2a71ddffb.png)

**Comment by itwt57** [comment]
config :
    "jsannotations.hideDiagnostics": true,
    "jsannotations.hideIfEqual": false,
    "jsannotations.hideInvalidAnnotation": false,
