### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by Lakitna** [lannonbr/vscode-js-annotations#84]
I really like this extension. It makes my life a lot easier :)

But I've noticed that some significant bugs that exist for everyone (most notably #66) are not fixed. In fact, the last release was almost a year ago on Mar 11, 2019.

Can I assume that this project has silently died or does the maintainer just not have time at the moment?

In either case. What's the way forward for the functionality this extension provides?

**Comment by pumpkinlink** [comment]
Seems like mantainer @lannonbr is absent since October 2019, maybe it's time for a voluntary to fork the project and take over?

**Comment by lannonbr** [comment]
Yeah personally I just haven't had the motivation to continue working on it, but I would be alright if it was forked.

**Comment by lannonbr** [comment]
I'm going to close this issue as I have opened #92 for my comments on this situation
